name: Examples

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - uses: yezz123/setup-uv@v4
      - name: Install dependencies
        working-directory: ./examples/weather
        run: |
          cd examples/weather
          uv pip install --system -r requirements.txt
      - name: Test
        working-directory: ./examples/weather
        run: pytest --cov --cov-branch --doctest-modules
      - uses: jakebailey/pyright-action@v2
      - name: Lint
        working-directory: ./examples/weather
        run: ruff check --output-format=github
      - name: Format
        working-directory: ./examples/weather
        run: ruff format --diff
