name: Examples

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - uses: eifinger/setup-rye@v4
      - name: Install workspace dependencies
        run: rye sync
      - name: Test
        working-directory: ./examples/weather
        run: ../../.venv/bin/pytest --cov --cov-branch --doctest-modules
      - uses: jakebailey/pyright-action@v2
      - name: Lint
        working-directory: ./examples/weather
        run: ../../.venv/bin/ruff check --output-format=github
      - name: Format
        working-directory: ./examples/weather
        run: ../../.venv/bin/ruff format --diff
